"""Static declaration of the compiled builtin; this is not a Python factory."""
from typing import Any

class FrozenBootstrapAuthority:
    def read_verified(self, entry_id: str) -> bytes: ...
    def module_reproof(self, entry_id: str) -> tuple[Any, ...]: ...
    def bind_producer(self, producer: object) -> bool: ...
    def close(self) -> None: ...

def is_producer(producer: object) -> bool: ...
