#!/usr/bin/env python3
"""Generate LocalCAT's pinned Unicode 16.0.0 matcher property tables.

The generator is intentionally offline.  Obtain the named files from the
official Unicode 16.0.0 UCD, place them in ``--source-dir``, and the SHA-256
gate below verifies every product-authoritative input before generation.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
from typing import Iterable


UNICODE_VERSION = "16.0.0"
SOURCE_FILES = {
    "PropList.txt": (
        "https://www.unicode.org/Public/16.0.0/ucd/PropList.txt",
        "53d614508e2a0b2305a8aa21cd60d993de9326cdf65993660dfcce4503548583",
    ),
    "Scripts.txt": (
        "https://www.unicode.org/Public/16.0.0/ucd/Scripts.txt",
        "9e88f0a677df47311106340be8ede2ecdacd9c1c931831218d2be6d5508e0039",
    ),
    "WordBreakProperty.txt": (
        "https://www.unicode.org/Public/16.0.0/ucd/auxiliary/WordBreakProperty.txt",
        "476464e71a4b7b779b8ba7c5671f4338fea77da8e6b6b05fb82b3fdd14603779",
    ),
    "emoji-data.txt": (
        "https://www.unicode.org/Public/16.0.0/ucd/emoji/emoji-data.txt",
        "f1365a5173eee18e1f98b240cdc492e84a25f1ce7e0c9d1094eb29c41a22696a",
    ),
}
_CJK_SCRIPTS = {"Han", "Hiragana", "Katakana", "Hangul"}


def _source_lines(path: Path) -> Iterable[str]:
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        payload = raw_line.split("#", 1)[0].strip()
        if payload:
            yield payload


def _code_point_range(raw_range: str) -> tuple[int, int]:
    if ".." in raw_range:
        start_raw, end_raw = raw_range.split("..", 1)
    else:
        start_raw = end_raw = raw_range
    return int(start_raw, 16), int(end_raw, 16)


def _property_ranges(
    path: Path,
    *,
    accepted: set[str] | None = None,
) -> list[tuple[int, int, str]]:
    ranges: list[tuple[int, int, str]] = []
    for payload in _source_lines(path):
        raw_range, raw_property = (
            item.strip() for item in payload.split(";", 1)
        )
        property_name = raw_property.split()[0]
        if accepted is not None and property_name not in accepted:
            continue
        start, end = _code_point_range(raw_range)
        ranges.append((start, end, property_name))
    return _merge_ranges(ranges)


def _merge_ranges(
    ranges: list[tuple[int, int, str]],
) -> list[tuple[int, int, str]]:
    merged: list[tuple[int, int, str]] = []
    for start, end, value in sorted(ranges):
        if merged and merged[-1][2] == value and merged[-1][1] + 1 == start:
            previous_start, _, previous_value = merged[-1]
            merged[-1] = (previous_start, end, previous_value)
        else:
            merged.append((start, end, value))
    return merged


def _validate_sources(source_dir: Path) -> dict[str, Path]:
    paths: dict[str, Path] = {}
    for name, (_, expected_digest) in SOURCE_FILES.items():
        path = source_dir / name
        if not path.is_file():
            raise SystemExit(f"missing Unicode source: {path}")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != expected_digest:
            raise SystemExit(
                f"Unicode source digest mismatch for {name}: {digest}"
            )
        paths[name] = path
    return paths


def _format_ranges(
    name: str,
    ranges: list[tuple[int, int, str]],
) -> str:
    lines = [f"{name} = ("]
    lines.extend(
        f"    (0x{start:04X}, 0x{end:04X}, {value!r}),"
        for start, end, value in ranges
    )
    lines.append(")")
    return "\n".join(lines)


def _format_boolean_ranges(
    name: str,
    ranges: list[tuple[int, int, str]],
) -> str:
    lines = [f"{name} = ("]
    lines.extend(
        f"    (0x{start:04X}, 0x{end:04X}),"
        for start, end, _ in ranges
    )
    lines.append(")")
    return "\n".join(lines)


def generate(source_dir: Path, output: Path) -> None:
    paths = _validate_sources(source_dir)
    word_break = _property_ranges(paths["WordBreakProperty.txt"])
    cjk_scripts = _property_ranges(
        paths["Scripts.txt"],
        accepted=_CJK_SCRIPTS,
    )
    variation_selectors = _property_ranges(
        paths["PropList.txt"],
        accepted={"Variation_Selector"},
    )
    extended_pictographic = _property_ranges(
        paths["emoji-data.txt"],
        accepted={"Extended_Pictographic"},
    )
    digest_lines = "\n".join(
        f"    {name!r}: {digest!r},"
        for name, (_, digest) in sorted(SOURCE_FILES.items())
    )
    url_lines = "\n".join(
        f"    {name!r}: {url!r},"
        for name, (url, _) in sorted(SOURCE_FILES.items())
    )
    content = f'''\
"""Generated pinned Unicode property tables for LocalCAT text-v1.

Generated by ``tools/generate_unicode_word_break_data.py`` from official
Unicode {UNICODE_VERSION} sources.  Do not edit by hand.
"""

from __future__ import annotations

from bisect import bisect_right


UNICODE_VERSION = {UNICODE_VERSION!r}
SOURCE_DIGESTS = {{
{digest_lines}
}}
SOURCE_URLS = {{
{url_lines}
}}

{_format_ranges("WORD_BREAK_RANGES", word_break)}

{_format_ranges("CJK_SCRIPT_RANGES", cjk_scripts)}

{_format_boolean_ranges("VARIATION_SELECTOR_RANGES", variation_selectors)}

{_format_boolean_ranges("EXTENDED_PICTOGRAPHIC_RANGES", extended_pictographic)}

_WORD_BREAK_STARTS = tuple(item[0] for item in WORD_BREAK_RANGES)
_CJK_SCRIPT_STARTS = tuple(item[0] for item in CJK_SCRIPT_RANGES)
_VARIATION_SELECTOR_STARTS = tuple(
    item[0] for item in VARIATION_SELECTOR_RANGES
)
_EXTENDED_PICTOGRAPHIC_STARTS = tuple(
    item[0] for item in EXTENDED_PICTOGRAPHIC_RANGES
)


def _range_value(
    code_point: int,
    ranges: tuple[tuple[int, int, str], ...],
    starts: tuple[int, ...],
) -> str | None:
    index = bisect_right(starts, code_point) - 1
    if index < 0:
        return None
    start, end, value = ranges[index]
    if start <= code_point <= end:
        return value
    return None


def _in_ranges(
    code_point: int,
    ranges: tuple[tuple[int, int], ...],
    starts: tuple[int, ...],
) -> bool:
    index = bisect_right(starts, code_point) - 1
    if index < 0:
        return False
    start, end = ranges[index]
    return start <= code_point <= end


def word_break_property(code_point: int) -> str:
    """Return the pinned UAX #29 Word_Break value, defaulting to Other."""

    return (
        _range_value(code_point, WORD_BREAK_RANGES, _WORD_BREAK_STARTS)
        or "Other"
    )


def cjk_script(code_point: int) -> str | None:
    """Return one of the four accepted pinned CJK Script values."""

    return _range_value(code_point, CJK_SCRIPT_RANGES, _CJK_SCRIPT_STARTS)


def is_variation_selector(code_point: int) -> bool:
    return _in_ranges(
        code_point,
        VARIATION_SELECTOR_RANGES,
        _VARIATION_SELECTOR_STARTS,
    )


def is_extended_pictographic(code_point: int) -> bool:
    return _in_ranges(
        code_point,
        EXTENDED_PICTOGRAPHIC_RANGES,
        _EXTENDED_PICTOGRAPHIC_STARTS,
    )


__all__ = [
    "SOURCE_DIGESTS",
    "SOURCE_URLS",
    "UNICODE_VERSION",
    "cjk_script",
    "is_extended_pictographic",
    "is_variation_selector",
    "word_break_property",
]
'''
    output.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    generate(args.source_dir, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
